### DISCUSSION TITLE
Ansible skips almost the whole process?

### DISCUSSION THREAD

**Discussion by uvulpos** [hifis-net/ansible-collection-toolkit#158] [Q&A] [answered]
Hi there,
I'm not an expert in Ansible, and I never used unattended-upgrades as a sysadmin before, but it looks strange to me that so many steps were skipped on my Hetzner ubuntu-22.04 server. Is that right? Is it configured as it used to be?

I would have expected `Test apt-daily timer expression` and `Deploy apt-daily timer` to be ok or at least status changed, but nope, skipped. Is that right? Is my configuration enough?

<img width="521" alt="Screenshot 2023-09-10 at 20 39 25" src="https://github.com/hifis-net/ansible-role-unattended-upgrades/assets/53957681/086beeb6-5c09-413b-b20a-1fa908da3a16">

## My Ansible playbook entry:
```yaml
- hosts: all
  roles:
    - role: hifis.unattended_upgrades
      unattended_origins_patterns:
        - "origin=Ubuntu,archive=${distro_codename}-security"
        - "o=Ubuntu,a=${distro_codename}"
        - "o=Ubuntu,a=${distro_codename}-updates"
        - "o=Ubuntu,a=${distro_codename}-proposed-updates"
```

## My Ansible version:
```
ansible-playbook [core 2.15.3]
  python version = 3.11.5 (main, Aug 24 2023, 15:09:45) [Clang 14.0.3 (clang-1403.0.22.14.1)] (/opt/homebrew/Cellar/ansible/8.3.0/libexec/bin/python)
  jinja version = 3.1.2
  libyaml = True
```
