### DISCUSSION TITLE
General question about combined use of keepalived/haproxy roles

### DISCUSSION THREAD

**Discussion by rog9876** [hifis-net/ansible-collection-toolkit#298] [Q&A]
Hi there,

Long time user of the unattended-upgrades role which has served me really well - Thanks for that!

I now also need to run a combination of keepalived and haproxy and the roles you have for these look very useful too. I just hoped you could help me understand how to run these together.

I'm looking at the roles here:
https://galaxy.ansible.com/ui/repo/published/hifis/toolkit/content/role/keepalived/
https://galaxy.ansible.com/ui/repo/published/hifis/toolkit/content/role/haproxy/

Looking at the example playbooks given, would I need to combine both? Am I correct to think that below should do the job?

```
- hosts: loadbalancers
  roles:
    - role: hifis.toolkit.haproxy
      vars:
        haproxy_frontend_ip: '192.168.33.100'
        haproxy_backends:
          - backend_name: 'backend_server_1'
            backend_ip: '192.168.33.15'
            backend_port: 80
          - backend_name: 'backend_server_2'
            backend_ip: '192.168.33.16'
            backend_port: 80
            
    - role: hifis.toolkit.keepalived
      vars:
        keepalived_virtual_ip_address: '192.168.33.100'
        keepalived_unicast_peers:
          - '192.168.33.15'
          - '192.168.33.16'
            
```
